In [3]:
## Basic attention model
from numpy import array
from numpy import random
from numpy import dot
from scipy.special import softmax
import numpy as np
import pandas as pd


# encoder representations of four different words
Action = array([1, 0, 0])
get = array([0, 1, 0])
result= array([1, 1, 0])
here = array([0, 0, 1])
words = array([Action, get, result, here])
max_seq_len = 4

# Generate positional encoding
positional_encoding = np.zeros((max_seq_len, words.shape[1]))
for pos in range(max_seq_len):
    for i in range(words.shape[1]):
        if i % 2 == 0:
            positional_encoding[pos, i] = np.sin(pos / 10000 ** (i / words.shape[1]))
        else:
            positional_encoding[pos, i] = np.cos(pos / 10000 ** ((i - 1) / words.shape[1]))
# Print the positional encoding values
for pos in range(max_seq_len):
    print(f"Position {pos}: {positional_encoding[pos]}")



# generating the weight matrices
random.seed(42)
W_Q = random.randint(3, size=(3, 3))
W_K = random.randint(3, size=(3, 3))
W_V = random.randint(3, size=(3, 3))

# generating the queries, keys and values
Q = words @ W_Q
K = words @ W_K
V = words @ W_V

# scoring the query vectors against all key vectors
scores = Q @ K.transpose()

# computing the weights by a softmax operation
weights = softmax(scores / K.shape[1] ** 0.5, axis=1)

# computing the attention by a weighted sum of the value vectors
attention = weights @ V

print(attention)
print("Data shape:", words.shape)
print("Positional Encoding shape:", positional_encoding.shape)
print("Weight Matrices shapes:", W_Q.shape, W_K.shape, W_V.shape)
print("Q, K, V shapes:", Q.shape, K.shape, V.shape)
print("Scores shape:", scores.shape)
print("Weights shape:", weights.shape)

Position 0: [0. 1. 0.]
Position 1: [0.84147098 0.54030231 0.00215443]
Position 2: [ 0.90929743 -0.41614684  0.00430886]
Position 3: [ 0.14112001 -0.9899925   0.00646326]
[[0.98522025 1.74174051 0.75652026]
 [0.90965265 1.40965265 0.5       ]
 [0.99851226 1.75849334 0.75998108]
 [0.99560386 1.90407309 0.90846923]]
Data shape: (4, 3)
Positional Encoding shape: (4, 3)
Weight Matrices shapes: (3, 3) (3, 3) (3, 3)
Q, K, V shapes: (4, 3) (4, 3) (4, 3)
Scores shape: (4, 4)
Weights shape: (4, 4)


In [7]:

# import librariestgfhrtyg
import numpy as np
import pandas as pd
from scipy.special import softmax

# Load your data from a CSV file with a raw string for the file path
data_set = pd.read_csv(r'C:\Users\IBOM-HB\Downloads\mdata.csv')

text = "My name is obasi yetunde I live in south korea"
tokens = text.split()
print(tokens)

# Create a DataFrame from the tokens
data = pd.DataFrame([tokens])

# Get unique words in the text
unique_words = list(set(tokens))

# Create a dictionary to map words to integer indices
word_to_index = {word: i for i, word in enumerate(unique_words)}

# Create an empty one-hot encoding DataFrame
one_hot_data = pd.DataFrame(0, columns=unique_words, index=[0])

# Fill in the one-hot encoding DataFrame
for word in tokens:
    one_hot_data.at[0, word] = 1

# Define max_seq_len based on the number of columns (words) in your data
max_seq_len = one_hot_data.shape[1]
positional_encoding = np.zeros((max_seq_len, one_hot_data.shape[1]))

# Generate positional encoding
for pos in range(max_seq_len):
    for i in range(one_hot_data.shape[1]):
        if i % 2 == 0:
            positional_encoding[pos, i] = np.sin(pos / 10000 ** (i / one_hot_data.shape[1]))
        else:
            positional_encoding[pos, i] = np.cos(pos / 10000 ** ((i - 1) / one_hot_data.shape[1]))

# Generating the weight matrices
np.random.seed(42)
W_Q = np.random.randint(10, size=(one_hot_data.shape[1], one_hot_data.shape[1]))
W_K = np.random.randint(10, size=(one_hot_data.shape[1], one_hot_data.shape[1]))
W_V = np.random.randint(10, size=(one_hot_data.shape[1], one_hot_data.shape[1]))

# Generating the queries, keys, and values
Q = one_hot_data @ W_Q
K = one_hot_data @ W_K
V = one_hot_data @ W_V

# Scoring the query vectors against all key vectors
scores = Q @ K.transpose()

# Computing the weights by a softmax operation
weights = softmax(scores / K.shape[1] ** 0.5, axis=1)

# Computing the attention by a weighted sum of the value vectors
attention = weights @ V

# Print the resulting attention
print(attention)


['My', 'name', 'is', 'obasi', 'yetunde', 'I', 'live', 'in', 'south', 'korea']
      0     1     2     3     4     5     6     7     8     9
0  32.0  31.0  51.0  35.0  43.0  35.0  31.0  45.0  45.0  38.0
