<a href="https://colab.research.google.com/github/olaopin5/obasi-yetunde/blob/main/homework_4_ipy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# New section

Homwork_4_1

In [ ]:
import numpy as np
arr_2d = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(arr_2d)
print(arr_2d[2,3])
print(arr_2d[1])
print(arr_2d[:,0])
## Reshape
reshaped_arr = arr_2d.reshape(4,3)
print(reshaped_arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
12
[5 6 7 8]
[1 5 9]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


Homework_4_2

In [ ]:
import numpy as np
arr_1 = np.array([1,2,3]) # first array
arr_2 = np.array([2,4,6]) # second array
print(arr_1 + arr_2) # Addition of the two array
print(arr_1 * arr_2) # multiplication of the two array
print(np.sum(arr_1)) # sum of the first array
print(np.sum(arr_2)) # sum of the second array
print(np.mean(arr_1)) # mean of the first array
print(np.mean(arr_2)) # mean of the second array

[3 6 9]
[ 2  8 18]
6
12
2.0
4.0


Homework_4_3

In [16]:
import numpy as np
data = np.loadtxt('/content/drive/MyDrive/Colab Notebooks/data.txt', delimiter=',')
print(data)
print(np.sum(data, axis=0))
transposed_data = np.transpose(data)
print(np.transpose)
New_file = 'transposed_data.csv'
print(New_file)


[[1. 2. 4.]
 [5. 8. 9.]
 [5. 4. 5.]]
[11. 14. 18.]
<function transpose at 0x7a48182e65f0>
transposed_data.csv


Homework_4_4

In [ ]:
import numpy as np
arr_2d = np.array([[1,2,3],[4,np.nan,6],[7,8,np.nan],[np.nan,4,6]])
print(arr_2d)
cleaned_arr = np.delete(arr_2d, np.where(np.isnan(arr_2d))[0], axis=0)
print(cleaned_arr)

[[ 1.  2.  3.]
 [ 4. nan  6.]
 [ 7.  8. nan]
 [nan  4.  6.]]
[[1. 2. 3.]]


Homework_4_5

In [18]:
import numpy as np
from scipy import stats
arr = ([4,6,8,10])
print(arr)
scaled_arr = (arr - np.min(arr)) / (np.max(arr) - np.min(arr))
print(scaled_arr)
arr_scaled = stats.zscore(arr)
print(arr_scaled)

[4, 6, 8, 10]
[0.         0.33333333 0.66666667 1.        ]
[-1.34164079 -0.4472136   0.4472136   1.34164079]
