sequence

In [ ]:
from keras.src.layers.rnn import Bidirectional
# import libraries
from numpy import array
from keras.models import Sequential
from keras.layers import LSTM, Dense

sample = [10, 20, 30, 40, 50, 60, 70, 80, 90,100,110,120,130,140,150]
X = [[10, 20, 30],[20, 30, 40],[30, 40, 50], [40, 50, 60], [50, 60, 70]]

y = [40, 50, 60]

# DEfine the function
def split_sequence(sequence, n_steps):
    X, y = list(), list()
    for i in range(len(sequence)):
        # find the end of this pattern
        end_ix = i + n_steps
        # check if we are beyond the sequence
        if end_ix > len(sequence)-1:
            break
        # gather input and output parts of the pattern
        seq_x, seq_y = sequence[i:end_ix], sequence[end_ix]
        X.append(seq_x)
        y.append(seq_y)
    return array(X), array(y)

# define input sequence
raw_seq = [10, 20, 30, 40, 50, 60, 70, 80, 90,100,110,120,130,140,150]
# choose a number of time steps
n_steps = 3
# split into samples
X, y = split_sequence(raw_seq, n_steps)
# summarize the data
for i in range(len(X)):
 print(X[i], y[i])


# Deine model
n_features = 1
model = Sequential()
model.add(Bidirectional(LSTM(50, activation='relu'), input_shape=(n_steps, n_features)))
model.add(Dense(1))
model.compile(optimizer='adam', loss='mse')

# Reshape X to have the shape [samples, timesteps, features]
X = X.reshape((X.shape[0], n_steps, n_features))

# fit model
model.fit(X, y, epochs=200, verbose = 0)
x_input = array([70, 80, 90])
x_input = x_input.reshape((1, n_steps, n_features))
y = model.predict(x_input, verbose=0)
print(y)

[10 20 30] 40
[20 30 40] 50
[30 40 50] 60
[40 50 60] 70
[50 60 70] 80
[60 70 80] 90
[70 80 90] 100
[ 80  90 100] 110
[ 90 100 110] 120
[100 110 120] 130
[110 120 130] 140
[120 130 140] 150


[[100.109085]]


Attention mechanism model

In [ ]:
from numpy import array
from numpy import random
from numpy import dot
from scipy.special import softmax
import numpy as np
import pandas as pd


# encoder representations of four different words
Action = array([1, 0, 0])
get = array([0, 1, 0])
result= array([1, 1, 0])
here = array([0, 0, 1])
max_seq_len = 4

# Generate positional encoding
positional_encoding = np.zeros((max_seq_len, words.shape[1]))
for pos in range(max_seq_len):
    for i in range(words.shape[1]):
        if i % 2 == 0:
            positional_encoding[pos, i] = np.sin(pos / 10000 ** (i / words.shape[1]))
        else:
            positional_encoding[pos, i] = np.cos(pos / 10000 ** ((i - 1) / words.shape[1]))
# Print the positional encoding values
for pos in range(max_seq_len):
    print(f"Position {pos}: {positional_encoding[pos]}")


# stacking the word embeddings into a single array
words = array([Action, get, result, here])

# generating the weight matrices
random.seed(42)
W_Q = random.randint(3, size=(3, 3))
W_K = random.randint(3, size=(3, 3))
W_V = random.randint(3, size=(3, 3))

# generating the queries, keys and values
Q = words @ W_Q
K = words @ W_K
V = words @ W_V

# scoring the query vectors against all key vectors
scores = Q @ K.transpose()

# computing the weights by a softmax operation
weights = softmax(scores / K.shape[1] ** 0.5, axis=1)

# computing the attention by a weighted sum of the value vectors
attention = weights @ V

print(attention)
print("Data shape:", words.shape)
print("Positional Encoding shape:", positional_encoding.shape)
print("Weight Matrices shapes:", W_Q.shape, W_K.shape, W_V.shape)
print("Q, K, V shapes:", Q.shape, K.shape, V.shape)
print("Scores shape:", scores.shape)
print("Weights shape:", weights.shape)


In [16]:
import numpy as np
import pandas as pd
from scipy.special import softmax

# Load your data from a CSV file
data_set = pd.read_csv('/content/mdata.csv')
text = "My name is obasi yetunde I live in south korea"
tokens = text.split()
print(tokens)

# Create a DataFrame from the tokens
data = pd.DataFrame([tokens])
data = pd.DataFrame()


unique_words = list(set(tokens))

for word in unique_words:
    data[word] = 0

for word in tokens:
    data.at[0, word] = 1

# Define max_seq_len based on the number of columns (words) in your data
max_seq_len = data.shape[1]
positional_encoding = np.zeros((max_seq_len, data.shape[1]))

# Generate positional encoding
positional_encoding = np.zeros((max_seq_len, data.shape[1]))
for pos in range(max_seq_len):
    for i in range(data.shape[1]):
        if i % 2 == 0:
            positional_encoding[pos, i] = np.sin(pos / 10000 ** (i / data.shape[1]))
        else:
            positional_encoding[pos, i] = np.cos(pos / 10000 ** ((i - 1) / data.shape[1]))

# Generating the weight matrices
np.random.seed(42)
W_Q = np.random.randint(10, size=(data.shape[1], data.shape[1]))
W_K = np.random.randint(10, size=(data.shape[1], data.shape[1]))
W_V = np.random.randint(10, size=(data.shape[1], data.shape[1]))

# Generating the queries, keys, and values
Q = data @ W_Q
K = data @ W_K
V = data @ W_V

# Scoring the query vectors against all key vectors
scores = Q @ K.transpose()

# Computing the weights by a softmax operation
weights = softmax(scores / K.shape[1] ** 0.5, axis=1)

# Computing the attention by a weighted sum of the value vectors
attention = weights @ V

# Print the resulting attention


print(attention)


['My', 'name', 'is', 'obasi', 'yetunde', 'I', 'live', 'in', 'south', 'korea']
      0     1     2     3     4     5     6     7     8     9
0  32.0  31.0  51.0  35.0  43.0  35.0  31.0  45.0  45.0  38.0


Attention mechanism based on model

In [ ]:
!pip install chart-studio

In [ ]:
!pip install chart-studio

import pandas as pd
import tensorflow as tf
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
import unicodedata
import re
import numpy as np
import time
import string
import os
import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))
# Set the file path here
file_path = ('/content/eng-fra.txt')

lines = open(file_path, encoding='UTF-8').read().strip().split('\n')
lines[5000:5010]


print("total number of records: ",len(lines))

exclude = set(string.punctuation) # Set of all special characters
remove_digits = str.maketrans('', '', string.digits) # Set of all digit

# function
def preprocess_eng_sentence(sent):
    '''Function to preprocess English sentence'''
    sent = sent.lower() # lower casing
    sent = re.sub("'", '', sent) # remove the quotation marks if any
    sent = ''.join(ch for ch in sent if ch not in exclude)
    sent = sent.translate(remove_digits) # remove the digits
    sent = sent.strip()
    sent = re.sub(" +", " ", sent) # remove extra spaces
    sent = '<start> ' + sent + ' <end>' # add <start> and <end> tokens
    return sent

def preprocess_french_sentence(sentence):
    # Your preprocessing code for French sentences
    preprocessed_sentence = sentence.lower()  # Example: Convert to lowercase
    preprocessed_sentence = '<start> ' + preprocessed_sentence + ' <end>'  # Add <start> and <end> tokens
    return preprocessed_sentence


sent_pairs = []
for line in lines:
    sent_pair = []
    eng = line.rstrip().split('\t')[0]
    french = line.rstrip().split('\t')[1]
    eng = preprocess_eng_sentence(eng)
    sent_pair.append(eng)
    french = preprocess_french_sentence(french)  # Call the function and store the result
    sent_pair.append(french)
    sent_pairs.append(sent_pair)

##
class LanguageIndex():
    def __init__(self, lang, add_start_end_tokens=False):
        self.lang = lang
        self.word2idx = {}
        self.idx2word = {}
        self.vocab = set()

        self.create_index(add_start_end_tokens)

    def create_index(self, add_start_end_tokens):
        if add_start_end_tokens:
            self.vocab.add("<start>")
            self.vocab.add("<end>")

        for phrase in self.lang:
            self.vocab.update(phrase.split(' '))

        self.vocab = sorted(self.vocab)

        self.word2idx['<pad>'] = 0
        for index, word in enumerate(self.vocab):
            self.word2idx[word] = index + 1

        for word, index in self.word2idx.items():
            self.idx2word[index] = word

inp_lang = LanguageIndex((en for en, ma in sent_pairs), add_start_end_tokens=True)
targ_lang = LanguageIndex((ma for en, ma in sent_pairs), add_start_end_tokens=True)



def max_length(tensor):
    return max(len(t) for t in tensor)
## Tokenization and padding
def load_dataset(pairs, num_examples):
    # pairs => already created cleaned input, output pairs

    # index language using the class defined above
    inp_lang = LanguageIndex(en for en, ma in pairs)
    targ_lang = LanguageIndex(ma for en, ma in pairs)

    # Vectorize the input and target languages

    # English sentences
    input_tensor = [[inp_lang.word2idx[s] for s in en.split(' ')] for en, ma in pairs]

    # Marathi sentences
    target_tensor = [[targ_lang.word2idx[s] for s in ma.split(' ')] for en, ma in pairs]

    # Calculate max_length of input and output tensor
    # Here, we'll set those to the longest sentence in the dataset
    max_length_inp, max_length_tar = max_length(input_tensor), max_length(target_tensor)

    # Padding the input and output tensor to the maximum length
    input_tensor = tf.keras.preprocessing.sequence.pad_sequences(input_tensor,
                                                                 maxlen=max_length_inp,
                                                                 padding='post')

    target_tensor = tf.keras.preprocessing.sequence.pad_sequences(target_tensor,
                                                                  maxlen=max_length_tar, padding='post')

    return input_tensor, target_tensor, inp_lang, targ_lang, max_length_inp, max_length_tar


input_tensor, target_tensor, inp_lang, targ_lang, max_length_inp, max_length_targ = load_dataset(sent_pairs, len(lines))

# Training and validation set 80-20
input_tensor_train, input_tensor_val, target_tensor_train, target_tensor_val = train_test_split(input_tensor, target_tensor, test_size=0.1, random_state = 101)

# Show length
len(input_tensor_train), len(target_tensor_train), len(input_tensor_val), len(target_tensor_val)

# parameters
BUFFER_SIZE = len(input_tensor_train)
BATCH_SIZE = 64
N_BATCH = BUFFER_SIZE//BATCH_SIZE
embedding_dim = 256
units = 1024
vocab_inp_size = len(inp_lang.word2idx)
vocab_tar_size = len(targ_lang.word2idx)

dataset = tf.data.Dataset.from_tensor_slices((input_tensor_train, target_tensor_train)).shuffle(BUFFER_SIZE)
dataset = dataset.batch(BATCH_SIZE, drop_remainder=True)

def lstm(units):

    return tf.keras.layers.LSTM(units,
                                   return_sequences=True,
                                   return_state=True,
                                   recurrent_activation='sigmoid',
                                   recurrent_initializer='glorot_uniform')

# encoder
class Encoder(tf.keras.Model):
    def __init__(self, vocab_size, embedding_dim, enc_units, batch_sz):
        super(Encoder, self).__init__()
        self.batch_sz = batch_sz
        self.enc_units = enc_units
        self.embedding = tf.keras.layers.Embedding(vocab_size, embedding_dim)
        self.lstm = lstm(self.enc_units)

    def call(self, x, hidden):
        x = self.embedding(x)
        output, state_h, state_c = self.lstm(x, initial_state=hidden)
        return output, (state_h, state_c)

    def initialize_hidden_state(self):
        return [tf.zeros((self.batch_sz, self.enc_units)), tf.zeros((self.batch_sz, self.enc_units))]


class Decoder(tf.keras.Model):
    def __init__(self, vocab_size, embedding_dim, dec_units, batch_sz):
        super(Decoder, self).__init__()
        self.batch_sz = batch_sz
        self.dec_units = dec_units
        self.embedding = tf.keras.layers.Embedding(vocab_size, embedding_dim)
        self.lstm = lstm(self.dec_units)  # Use 'gru' instead of 'lstm'
        self.fc = tf.keras.layers.Dense(vocab_size)

        # used for attention
        self.W1 = tf.keras.layers.Dense(self.dec_units)
        self.W2 = tf.keras.layers.Dense(self.dec_units)
        self.V = tf.keras.layers.Dense(1)

    def call(self, x, hidden, enc_output):
        hidden_with_time_axis = tf.expand_dims(hidden[0], 1)
        score = self.V(tf.nn.tanh(self.W1(enc_output) + self.W2(hidden_with_time_axis)))

        score = self.V(tf.nn.tanh(self.W1(enc_output) + self.W2(hidden_with_time_axis)))

        attention_weights = tf.nn.softmax(score, axis=1)
        context_vector = attention_weights * enc_output
        context_vector = tf.reduce_sum(context_vector, axis=1)

        x = self.embedding(x)
        x = tf.concat([tf.expand_dims(context_vector, 1), x], axis=-1)

        output, state_h, state_c = self.lstm(x, initial_state=hidden)  # Initialize the LSTM with the hidden state

        output = tf.reshape(output, (-1, output.shape[2]))

        x = self.fc(output)

        return x, [state_h, state_c], attention_weights


    def initialize_hidden_state(self):
        #
        return [tf.zeros((self.batch_sz, self.dec_units), dtype=tf.float32)] * 2


# Add '<start>' token to the target language vocabulary


encoder = Encoder(vocab_inp_size, embedding_dim, units, BATCH_SIZE)
decoder = Decoder(vocab_tar_size, embedding_dim, units, BATCH_SIZE)

# Define the loss function
def loss_function(real, pred):
      mask = tf.math.logical_not(tf.math.equal(real, 0))
      loss_ = tf.keras.losses.sparse_categorical_crossentropy(real, pred, from_logits=True)
      mask = tf.cast(mask, dtype=loss_.dtype)
      loss_ *= mask
      return tf.reduce_mean(loss_)

## Training the model
optimizer = tf.keras.optimizers.Adam()
EPOCHS = 10

for epoch in range(EPOCHS):
    start = time.time()

    hidden = encoder.initialize_hidden_state()
    total_loss = 0

    for (batch, (inp, targ)) in enumerate(dataset):
        loss = 0

        with tf.GradientTape() as tape:
            enc_output, enc_hidden = encoder(inp, hidden)

            dec_hidden = enc_hidden


            dec_input = tf.expand_dims([targ_lang.word2idx['<start>']] * BATCH_SIZE, 1)


            # Teacher forcing - feeding the target as the next input
            for t in range(1, targ.shape[1]):
                # passing enc_output to the decoder
                predictions, dec_hidden, _ = decoder(dec_input, dec_hidden, enc_output)
                loss += loss_function(targ[:, t], predictions)

                # using teacher forcing
                dec_input = tf.expand_dims(targ[:, t], 1)

        batch_loss = (loss / int(targ.shape[1]))

        total_loss += batch_loss

        variables = encoder.variables + decoder.variables

        gradients = tape.gradient(loss, variables)

        optimizer.apply_gradients(zip(gradients, variables))

        if batch % 100 == 0:
            print('Epoch {} Batch {} Loss {:.4f}'.format(epoch + 1,
                                                         batch,
                                                         batch_loss.numpy()))
    # saving (checkpoint) the model every epoch
    checkpoint.save(file_prefix = checkpoint_prefix)

    print('Epoch {} Loss {:.4f}'.format(epoch + 1,
                                        total_loss / N_BATCH))
    print('Time taken for 1 epoch {} sec\n'.format(time.time() - start))

total number of records:  135842
Epoch 1 Batch 0 Loss 1.4211
